import { Geist, Lexend } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  weigtht: ['300', '400', '500', '700'],
});

export const metadata = {
  title: "Devon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} ${geistSans.variable} antialiased dark:text-white`}>
        <header>
          <Navbar/>
        </header>
        {children}
      </body>
    </html>
  );
}
